version: "3"
services:
    app:
       build: .
       environment:
          - ALLOW_OVERRIDE=true
       ports:
          - "9059:80"
       volumes:
          - ./web:/var/www/html
          - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
          - ./apache/apache2.conf:/etc/apache2/apache2.conf
          - ./apache/security.conf:/etc/apache2/conf-enabled/security.conf
          - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    db:
        image: mariadb
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: database
        ports:
            - "8899:3306"   
             